# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/letv/s2/setup-makefiles.sh

VENDOR_PATH := vendor/letv/s2

PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/proprietary/lib64/hw/sensors.msm8952.so:lib64/hw/sensors.msm8952.so \
    $(VENDOR_PATH)/proprietary/lib64/hw/lights.msm8952.so:lib64/hw/lights.msm8952.so \
    $(VENDOR_PATH)/proprietary/lib/hw/sensors.msm8952.so:lib/hw/sensors.msm8952.so \
    $(VENDOR_PATH)/proprietary/lib/hw/lights.msm8952.so:lib/hw/lights.msm8952.so \
    $(VENDOR_PATH)/proprietary/lib/hw/camera.msm8952.so:lib/hw/camera.msm8952.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libacdbloader.so:vendor/lib64/libacdbloader.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/librs_adreno_sha1.so:vendor/lib64/librs_adreno_sha1.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libC2D2.so:vendor/lib64/libC2D2.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libadreno_utils.so:vendor/lib64/libadreno_utils.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libacdbrtac.so:vendor/lib64/libacdbrtac.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libc2d30-a4xx.so:vendor/lib64/libc2d30-a4xx.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libOpenCL.so:vendor/lib64/libOpenCL.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libCB.so:vendor/lib64/libCB.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libRSDriver_adreno.so:vendor/lib64/libRSDriver_adreno.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libllvm-qcom.so:vendor/lib64/libllvm-qcom.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libacdb-fts.so:vendor/lib64/libacdb-fts.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/librs_adreno.so:vendor/lib64/librs_adreno.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libc2d30-a3xx.so:vendor/lib64/libc2d30-a3xx.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libc2d30_bltlib.so:vendor/lib64/libc2d30_bltlib.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libscale.so:vendor/lib64/libscale.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libc2d30-a5xx.so:vendor/lib64/libc2d30-a5xx.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libacdbmapper.so:vendor/lib64/libacdbmapper.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libtime_genoff.so:vendor/lib64/libtime_genoff.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/egl/libq3dtools_adreno.so:vendor/lib64/egl/libq3dtools_adreno.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/egl/libQTapGLES.so:vendor/lib64/egl/libQTapGLES.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/egl/libq3dtools_esx.so:vendor/lib64/egl/libq3dtools_esx.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/egl/libGLESv2_adreno.so:vendor/lib64/egl/libGLESv2_adreno.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/egl/libGLESv1_CM_adreno.so:vendor/lib64/egl/libGLESv1_CM_adreno.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/egl/libEGL_adreno.so:vendor/lib64/egl/libEGL_adreno.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/egl/eglSubDriverAndroid.so:vendor/lib64/egl/eglSubDriverAndroid.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libbccQTI.so:vendor/lib64/libbccQTI.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libllvm-glnext.so:vendor/lib64/libllvm-glnext.so \
    $(VENDOR_PATH)/proprietary/vendor/lib64/libgsl.so:vendor/lib64/libgsl.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libacdbloader.so:vendor/lib/libacdbloader.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/librs_adreno_sha1.so:vendor/lib/librs_adreno_sha1.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libC2D2.so:vendor/lib/libC2D2.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libadreno_utils.so:vendor/lib/libadreno_utils.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libacdbrtac.so:vendor/lib/libacdbrtac.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libc2d30-a4xx.so:vendor/lib/libc2d30-a4xx.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libOpenCL.so:vendor/lib/libOpenCL.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libCB.so:vendor/lib/libCB.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libRSDriver_adreno.so:vendor/lib/libRSDriver_adreno.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libllvm-qcom.so:vendor/lib/libllvm-qcom.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libacdb-fts.so:vendor/lib/libacdb-fts.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/librs_adreno.so:vendor/lib/librs_adreno.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libc2d30-a3xx.so:vendor/lib/libc2d30-a3xx.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libc2d30_bltlib.so:vendor/lib/libc2d30_bltlib.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libscale.so:vendor/lib/libscale.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libc2d30-a5xx.so:vendor/lib/libc2d30-a5xx.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libacdbmapper.so:vendor/lib/libacdbmapper.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libtime_genoff.so:vendor/lib/libtime_genoff.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/egl/libq3dtools_adreno.so:vendor/lib/egl/libq3dtools_adreno.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/egl/libQTapGLES.so:vendor/lib/egl/libQTapGLES.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/egl/libq3dtools_esx.so:vendor/lib/egl/libq3dtools_esx.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/egl/libGLESv2_adreno.so:vendor/lib/egl/libGLESv2_adreno.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:vendor/lib/egl/libGLESv1_CM_adreno.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/egl/libEGL_adreno.so:vendor/lib/egl/libEGL_adreno.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:vendor/lib/egl/eglSubDriverAndroid.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libbccQTI.so:vendor/lib/libbccQTI.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libllvm-glnext.so:vendor/lib/libllvm-glnext.so \
    $(VENDOR_PATH)/proprietary/vendor/lib/libgsl.so:vendor/lib/libgsl.so \
    $(VENDOR_PATH)/proprietary/etc/firmware/a420_pfp.fw:etc/firmware/a420_pfp.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/goodixfp.b00:etc/firmware/goodixfp.b00 \
    $(VENDOR_PATH)/proprietary/etc/firmware/a300_pfp.fw:etc/firmware/a300_pfp.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/a330_pfp.fw:etc/firmware/a330_pfp.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/a530_pm4.fw:etc/firmware/a530_pm4.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/venus-v1.mdt:etc/firmware/venus-v1.mdt \
    $(VENDOR_PATH)/proprietary/etc/firmware/widevine.b01:etc/firmware/widevine.b01 \
    $(VENDOR_PATH)/proprietary/etc/firmware/venus-v1.mbn:etc/firmware/venus-v1.mbn \
    $(VENDOR_PATH)/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:etc/firmware/cpp_firmware_v1_1_1.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/venus.b04:etc/firmware/venus.b04 \
    $(VENDOR_PATH)/proprietary/etc/firmware/widevine.b02:etc/firmware/widevine.b02 \
    $(VENDOR_PATH)/proprietary/etc/firmware/goodixfp.b02:etc/firmware/goodixfp.b02 \
    $(VENDOR_PATH)/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:etc/firmware/cpp_firmware_v1_2_0.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/fidotap.b00:etc/firmware/fidotap.b00 \
    $(VENDOR_PATH)/proprietary/etc/firmware/alipay.b02:etc/firmware/alipay.b02 \
    $(VENDOR_PATH)/proprietary/etc/firmware/alipay.b03:etc/firmware/alipay.b03 \
    $(VENDOR_PATH)/proprietary/etc/firmware/a330_pm4.fw:etc/firmware/a330_pm4.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/leia_pfp_470.fw:etc/firmware/leia_pfp_470.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:etc/firmware/cpp_firmware_v1_1_6.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/alipay.b01:etc/firmware/alipay.b01 \
    $(VENDOR_PATH)/proprietary/etc/firmware/fidotap.mbn:etc/firmware/fidotap.mbn \
    $(VENDOR_PATH)/proprietary/etc/firmware/venus-v1.b04:etc/firmware/venus-v1.b04 \
    $(VENDOR_PATH)/proprietary/etc/firmware/ice40.bin:etc/firmware/ice40.bin \
    $(VENDOR_PATH)/proprietary/etc/firmware/widevine.b00:etc/firmware/widevine.b00 \
    $(VENDOR_PATH)/proprietary/etc/firmware/widevine.b03:etc/firmware/widevine.b03 \
    $(VENDOR_PATH)/proprietary/etc/firmware/widevine.mdt:etc/firmware/widevine.mdt \
    $(VENDOR_PATH)/proprietary/etc/firmware/cpp_firmware_v1_10_0.fw:etc/firmware/cpp_firmware_v1_10_0.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/goodixfp.mdt:etc/firmware/goodixfp.mdt \
    $(VENDOR_PATH)/proprietary/etc/firmware/fidotap.b03:etc/firmware/fidotap.b03 \
    $(VENDOR_PATH)/proprietary/etc/firmware/a225_pfp.fw:etc/firmware/a225_pfp.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/dxhdcp2.b01:etc/firmware/dxhdcp2.b01 \
    $(VENDOR_PATH)/proprietary/etc/firmware/a530_pfp.fw:etc/firmware/a530_pfp.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:etc/firmware/cpp_firmware_v1_4_0.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/fidotap.b02:etc/firmware/fidotap.b02 \
    $(VENDOR_PATH)/proprietary/etc/firmware/dxhdcp2.b02:etc/firmware/dxhdcp2.b02 \
    $(VENDOR_PATH)/proprietary/etc/firmware/leia_pm4_470.fw:etc/firmware/leia_pm4_470.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/venus-v1.b00:etc/firmware/venus-v1.b00 \
    $(VENDOR_PATH)/proprietary/etc/firmware/dxhdcp2.b03:etc/firmware/dxhdcp2.b03 \
    $(VENDOR_PATH)/proprietary/etc/firmware/DE.o.msm8976:etc/firmware/DE.o.msm8976 \
    $(VENDOR_PATH)/proprietary/etc/firmware/cpp_firmware_v1_5_0.fw:etc/firmware/cpp_firmware_v1_5_0.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/venus.b03:etc/firmware/venus.b03 \
    $(VENDOR_PATH)/proprietary/etc/firmware/DE.o.msm8952:etc/firmware/DE.o.msm8952 \
    $(VENDOR_PATH)/proprietary/etc/firmware/alipay.mdt:etc/firmware/alipay.mdt \
    $(VENDOR_PATH)/proprietary/etc/firmware/venus-v1.b03:etc/firmware/venus-v1.b03 \
    $(VENDOR_PATH)/proprietary/etc/firmware/venus.b02:etc/firmware/venus.b02 \
    $(VENDOR_PATH)/proprietary/etc/firmware/venus-v1.b02:etc/firmware/venus-v1.b02 \
    $(VENDOR_PATH)/proprietary/etc/firmware/goodixfp.b03:etc/firmware/goodixfp.b03 \
    $(VENDOR_PATH)/proprietary/etc/firmware/cpp_firmware_v1_6_0.fw:etc/firmware/cpp_firmware_v1_6_0.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/venus.mbn:etc/firmware/venus.mbn \
    $(VENDOR_PATH)/proprietary/etc/firmware/a225_pm4.fw:etc/firmware/a225_pm4.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/goodixfp.b01:etc/firmware/goodixfp.b01 \
    $(VENDOR_PATH)/proprietary/etc/firmware/venus.mdt:etc/firmware/venus.mdt \
    $(VENDOR_PATH)/proprietary/etc/firmware/venus.b00:etc/firmware/venus.b00 \
    $(VENDOR_PATH)/proprietary/etc/firmware/fidotap.mdt:etc/firmware/fidotap.mdt \
    $(VENDOR_PATH)/proprietary/etc/firmware/venus-v1.b01:etc/firmware/venus-v1.b01 \
    $(VENDOR_PATH)/proprietary/etc/firmware/a225p5_pm4.fw:etc/firmware/a225p5_pm4.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/alipay.b00:etc/firmware/alipay.b00 \
    $(VENDOR_PATH)/proprietary/etc/firmware/dxhdcp2.mdt:etc/firmware/dxhdcp2.mdt \
    $(VENDOR_PATH)/proprietary/etc/firmware/cpp_firmware_v1_8_0.fw:etc/firmware/cpp_firmware_v1_8_0.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/a300_pm4.fw:etc/firmware/a300_pm4.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin:etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin \
    $(VENDOR_PATH)/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv_nofem.bin:etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv_nofem.bin \
    $(VENDOR_PATH)/proprietary/etc/firmware/a420_pm4.fw:etc/firmware/a420_pm4.fw \
    $(VENDOR_PATH)/proprietary/etc/firmware/dxhdcp2.b00:etc/firmware/dxhdcp2.b00 \
    $(VENDOR_PATH)/proprietary/etc/firmware/fidotap.b01:etc/firmware/fidotap.b01 \
    $(VENDOR_PATH)/proprietary/etc/firmware/venus.b01:etc/firmware/venus.b01
